version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    image: wa3i_web:latest
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - wa3i_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=teamlab
      - POSTGRES_PASSWORD=teamlab_password
      - POSTGRES_DB=wa3i_dev
  sentence-analysis:
    build: ./sentence-analysis
    command: flask run
    ports:
      - 5252:5252
    env_file:
      - ./.env.sentence_api
    volumes:
      - ./sentence-analysis/:/usr/src/app/
  scoring-api:
    build: ./scoring-api
    command: conda run -n wai flask run
    ports:
      - 5000:5000
    environment:
      - POSTGRES_USER=teamlab
      - POSTGRES_PASSWORD=teamlab_password
      - POSTGRES_DB=wa3i_dev
    env_file:
      - ./.env.scoring_api
    volumes:
      - ./scoring-api/:/usr/src/app/
    depends_on:
      - db

volumes:
  wa3i_postgres_data:
