# Generated by Django 3.0.4 on 2020-05-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('assignment_id', models.TextField(blank=True, null=True)),
                ('teacher_id', models.BigIntegerField(blank=True, null=True)),
                ('assignment_title', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('start_date', models.TextField(blank=True, null=True)),
                ('end_date', models.TextField(blank=True, null=True)),
                ('made_date', models.TextField(blank=True, null=True)),
                ('grade', models.BigIntegerField(blank=True, null=True)),
                ('class_field', models.BigIntegerField(blank=True, db_column='class', null=True)),
            ],
            options={
                'db_table': 'assignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentQuestionRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('as_qurel_id', models.BigIntegerField(blank=True, null=True)),
                ('assignment_id', models.TextField(blank=True, null=True)),
                ('question_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assignment_question_rel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('category_id', models.BigIntegerField(blank=True, null=True)),
                ('category_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryQuestionRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('cate_qurel_id', models.BigIntegerField(blank=True, null=True)),
                ('question_id', models.BigIntegerField(blank=True, null=True)),
                ('category_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category_question_rel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('keyword_iid', models.BigIntegerField(blank=True, null=True)),
                ('question_id', models.BigIntegerField(blank=True, null=True)),
                ('keyword_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MakeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('make_question_id', models.BigIntegerField(blank=True, null=True)),
                ('teacher_id', models.BigIntegerField(blank=True, null=True)),
                ('question_name', models.TextField(blank=True, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('ques_concept', models.TextField(blank=True, null=True)),
                ('check', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'make_question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('question_id', models.BigIntegerField(blank=True, null=True)),
                ('category_id', models.BigIntegerField(blank=True, null=True)),
                ('model_id', models.BigIntegerField(blank=True, null=True)),
                ('question_name', models.TextField(blank=True, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('made_date', models.TextField(blank=True, null=True)),
                ('qr_code', models.TextField(blank=True, db_column='QR_code', null=True)),
                ('ques_concept', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SelfSolveData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('self_id', models.BigIntegerField(blank=True, null=True)),
                ('make_question_id', models.BigIntegerField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('score', models.BigIntegerField(blank=True, null=True)),
                ('submit_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'self_solve_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('solve_id', models.BigIntegerField(blank=True, null=True)),
                ('student_id', models.BigIntegerField(blank=True, null=True)),
                ('assignment_id', models.TextField(blank=True, null=True)),
                ('modified_date', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('score', models.BigIntegerField(blank=True, null=True)),
                ('student_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudySolveData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('study_id', models.BigIntegerField(blank=True, null=True)),
                ('question_id', models.BigIntegerField(blank=True, null=True)),
                ('school', models.TextField(blank=True, null=True)),
                ('sex', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('score', models.BigIntegerField(blank=True, null=True)),
                ('submit_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'study_solve_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('teacher_id', models.BigIntegerField(blank=True, null=True)),
                ('teacher_name', models.TextField(blank=True, null=True)),
                ('school', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('password', models.BigIntegerField(blank=True, null=True)),
                ('approve', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
    ]
